// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKfIMl9qysBgpguYb8omoiUuY_Ixg4ZTw',
    appId: '1:585377902354:web:3da910e225e4275e984dcb',
    messagingSenderId: '585377902354',
    projectId: 'blogapp-7ea1e',
    authDomain: 'blogapp-7ea1e.firebaseapp.com',
    storageBucket: 'blogapp-7ea1e.appspot.com',
    measurementId: 'G-79B145HCZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoIK1Cxn-qJsRFwk5f4380uIxiimVPiiM',
    appId: '1:585377902354:android:1bf83af44f7cba34984dcb',
    messagingSenderId: '585377902354',
    projectId: 'blogapp-7ea1e',
    storageBucket: 'blogapp-7ea1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANeFk2slbccZ_E3k3u3X1wOJXMMnM9624',
    appId: '1:585377902354:ios:9f43369d4e6b5dff984dcb',
    messagingSenderId: '585377902354',
    projectId: 'blogapp-7ea1e',
    storageBucket: 'blogapp-7ea1e.appspot.com',
    iosBundleId: 'com.example.blogapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANeFk2slbccZ_E3k3u3X1wOJXMMnM9624',
    appId: '1:585377902354:ios:9f43369d4e6b5dff984dcb',
    messagingSenderId: '585377902354',
    projectId: 'blogapp-7ea1e',
    storageBucket: 'blogapp-7ea1e.appspot.com',
    iosBundleId: 'com.example.blogapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKfIMl9qysBgpguYb8omoiUuY_Ixg4ZTw',
    appId: '1:585377902354:web:74fee24d89d5477d984dcb',
    messagingSenderId: '585377902354',
    projectId: 'blogapp-7ea1e',
    authDomain: 'blogapp-7ea1e.firebaseapp.com',
    storageBucket: 'blogapp-7ea1e.appspot.com',
    measurementId: 'G-YSYDLKGMF5',
  );
}
